name: Deploy a Firebase Hosting
on:
  push:
    branches:
      - main # Cambia esto si tu rama principal se llama 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Instalar Dependencias
        run: npm install

      - name: Construir Proyecto
        run: npm run build

      - name: Desplegar a Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
