name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build
        # Usamos npm install para evitar el error de falta de lockfile
        run: npm install && npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # Usamos el nombre exacto de tu secreto
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          # CORRECCIÃ“N: Usamos el ID de tu proyecto de Firebase Hosting
          projectId: cafestore-ffbec
