name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main # O el nombre de tu rama principal
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build
        run: npm ci && npm run build
        env:
          # Aqu√≠ inyectamos la llave que ya guardaste en Secrets
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COFFEE_POS }}'
          channelId: live
          projectId: gen-lang-client-0787100173
